<?php
/**
 * Created by PhpStorm.
 * User: TakayamaAren
 * Date: 11/17/2017
 * Time: 5:11 PM
 */

namespace App\Controller;


use App\Model\Entity\Article;
use App\Model\Entity\Personalize;
use App\Model\Table\ArticleTable;
use Cake\Controller\Controller;
use Cake\Filesystem\File;
use Cake\ORM\TableRegistry;

class MainController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $token = $this->Cookie->read('token');
        if($token == null){
            $this->redirect('login');
        }
        $userId = TableRegistry::get('Auth')->find()->where(["token_key"=>$this->Cookie->read('token')])->toArray()[0]->user;
        $user = TableRegistry::get('User')->find()->where(['id'=>$userId])->toArray()[0];
        $this->set("username",$user->username);

    }

    public function index()
    {

        $this->set('tabIndex','home');
    }

    public function login()
    {

    }

    public function signUp()
    {

    }

    public function article()
    {
        $token = $this->Cookie->read('token');
        if($token == null){
            $this->redirect('login');
        }

        $query = TableRegistry::get('Article')->find();
        $this->set('articleList', $query->toArray());
        $this->set('tabIndex','article');
    }

    public function createArticle()
    {
        $token = $this->Cookie->read('token');
        if($token == null){
            $this->redirect('login');
        }
        $this->set('tabIndex','article');
        $this->set('categoryList',TableRegistry::get('Category')->find()->toArray());
    }

    public function profile()
    {
        $token = $this->Cookie->read('token');
        if($token == null){
            $this->redirect('login');
        }
        $this->set('tabIndex','profile');



    }
    public function category(){
        $token = $this->Cookie->read('token');
        if($token == null){
            $this->redirect('login');
        }
        $this->set('tabIndex','category');

        $this->set('categoryList',TableRegistry::get('Category')->find()->toArray());

    }
    public function modifyProfile(){
        $personalize = new Personalize();
        $personalize->title = 'changed title';
        $personalize->save();
        $this->redirect('/admin/profile');
    }
}
